version: '3'
services: 
  web: 
    build: .
    ports: 
      - "8000:8000"
  db: 
    images: "mysql"
    enviroment: 
      MYSQL_ROOT_PASSWORD: password_goes_here
    volumes: 
      - db-data:/db
  volumes: 
    db-data: 